import { randomUUID as nodeRandomUUID } from 'node:crypto';

/**
 * Jest mock for `expo-crypto` (mapped in `jest.config.js`) — its real `randomUUID()` calls into
 * a native CSPRNG with no headless equivalent under Jest. Node's own `crypto.randomUUID` (global
 * since Node 19, available in this repo's Node 20+ engines requirement) is a fine stand-in: a
 * real, valid, unique UUID, just generated by a different CSPRNG than the one this module wraps
 * on-device.
 */
export function randomUUID(): string {
  return nodeRandomUUID();
}
